# Generated by Django 3.1.4 on 2020-12-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201216_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='location_name',
            new_name='name',
        ),
    ]
