# Generated by Django 3.1.4 on 2020-12-20 01:36

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 36, 2, 288019, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 1, 36, 20, 471921, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
