# Generated by Django 3.1.4 on 2020-12-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201220_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
